name: Auto Generate Blog Post

on:
  schedule:
    # 매일 0시, 3시, 6시, 9시, 12시, 15시, 18시, 21시에 실행 (UTC 기준)
    - cron: '0 */3 * * *'
  
  # 수동으로 워크플로우를 실행할 수 있는 옵션
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Install Canvas dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
      
      - name: Generate blog post
        id: generate-post
        run: node scripts/create-post-github-action.cjs
        env:
          PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
          PUBLIC_SITE_NAME: ${{ secrets.PUBLIC_SITE_NAME }}
          PUBLIC_SITE_DESCRIPTION: ${{ secrets.PUBLIC_SITE_DESCRIPTION }}
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/posts public/images/posts
          git diff --quiet && git diff --staged --quiet || git commit -m "자동 포스트 생성: $(date +'%Y-%m-%d %H:%M')"
          git push origin main 