name: 자동 블로그 포스트 생성

on:
  schedule:
    # 3시간마다 실행 (8회/일)
    - cron: '0 */3 * * *'
  # 수동 실행 가능하도록 워크플로우 디스패치 추가
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest
    
    steps:
      - name: 코드 체크아웃
        uses: actions/checkout@v3
      
      - name: Node.js 설정
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: 의존성 설치
        run: npm ci
      
      - name: Canvas 의존성 설치 (이미지 생성용)
        run: |
          sudo apt-get update
          sudo apt-get install -y libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev build-essential g++
      
      - name: 포스트 생성
        run: node scripts/create-post-github-action.cjs
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL || 'http://localhost:4321' }}
          PUBLIC_SITE_NAME: ${{ secrets.PUBLIC_SITE_NAME || '메리의 미수다' }}
          PUBLIC_SITE_DESCRIPTION: ${{ secrets.PUBLIC_SITE_DESCRIPTION || '중년 여성의 아름다움과 건강을 위한 실용적인 정보를 제공하는 블로그' }}
      
      - name: 변경사항 커밋
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git diff --quiet && git diff --staged --quiet || git commit -m "자동 블로그 포스트 생성: $(date +'%Y-%m-%d %H:%M:%S')"
      
      - name: 변경사항 푸시
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
